// 333 教育综合四科 + 章节骨架（官方考研大纲）
export const SUBJECTS = [
  {
    slug: "principles",
    title: "教育学原理",
    score: 100,
    summary: "333 核心科目，占 100 分。考教育基本理论、教育目的、课程、教学、德育、学校管理。",
    orderIdx: 1,
    chapters: [
      { slug: "1", title: "第一章　教育与教育学" },
      { slug: "2", title: "第二章　教育的功能" },
      { slug: "3", title: "第三章　教育目的" },
      { slug: "4", title: "第四章　教育制度" },
      { slug: "5", title: "第五章　教师与学生" },
      { slug: "6", title: "第六章　课程" },
      { slug: "7", title: "第七章　教学" },
      { slug: "8", title: "第八章　德育" },
      { slug: "9", title: "第九章　班主任与班级管理" },
      { slug: "10", title: "第十章　学校管理" },
      { slug: "11", title: "第十一章　教育研究及其方法" },
    ],
  },
  {
    slug: "china-history",
    title: "中国教育史",
    score: 50,
    summary: "从先秦到近现代，重点人物与制度：孔子、朱熹、蔡元培、陶行知、科举、壬戌学制等。",
    orderIdx: 2,
    chapters: [
      { slug: "1", title: "第一章　西周官学与春秋私学" },
      { slug: "2", title: "第二章　儒墨道法诸家教育思想" },
      { slug: "3", title: "第三章　封建国家教育体制的完备" },
      { slug: "4", title: "第四章　理学教育思想与学校的改革" },
      { slug: "5", title: "第五章　早期启蒙教育思想" },
      { slug: "6", title: "第六章　中国教育的近代转折" },
      { slug: "7", title: "第七章　近代教育体系的建立" },
      { slug: "8", title: "第八章　近代教育体制的变革" },
      { slug: "9", title: "第九章　南京国民政府的教育" },
      { slug: "10", title: "第十章　中国共产党领导下的教育" },
    ],
  },
  {
    slug: "world-history",
    title: "外国教育史",
    score: 50,
    summary: "古希腊到当代西方，苏格拉底、夸美纽斯、卢梭、赫尔巴特、杜威、苏霍姆林斯基等。",
    orderIdx: 3,
    chapters: [
      { slug: "1", title: "第一章　东方文明古国的教育" },
      { slug: "2", title: "第二章　古希腊罗马教育" },
      { slug: "3", title: "第三章　西欧中世纪教育" },
      { slug: "4", title: "第四章　文艺复兴与宗教改革教育" },
      { slug: "5", title: "第五章　欧美主要国家与日本近代教育" },
      { slug: "6", title: "第六章　19 世纪欧美教育思想" },
      { slug: "7", title: "第七章　欧美主要国家与日本现代教育" },
      { slug: "8", title: "第八章　现代欧美教育思潮" },
      { slug: "9", title: "第九章　苏联教育的发展" },
      { slug: "10", title: "第十章　战后主要发达国家教育改革" },
    ],
  },
  {
    slug: "psychology",
    title: "教育心理学",
    score: 50,
    summary: "学习理论、动机、迁移、认知发展、问题解决、品德形成等。皮亚杰、维果斯基、班杜拉重点。",
    orderIdx: 4,
    chapters: [
      { slug: "1", title: "第一章　教育心理学概述" },
      { slug: "2", title: "第二章　心理发展与教育" },
      { slug: "3", title: "第三章　学习的主要理论" },
      { slug: "4", title: "第四章　学习动机" },
      { slug: "5", title: "第五章　知识的建构" },
      { slug: "6", title: "第六章　技能的形成" },
      { slug: "7", title: "第七章　学习策略及其教学" },
      { slug: "8", title: "第八章　问题解决能力与创造性的培养" },
      { slug: "9", title: "第九章　社会规范学习与品德发展" },
      { slug: "10", title: "第十章　心理健康及其教育" },
      { slug: "11", title: "第十一章　教师心理" },
      { slug: "12", title: "第十二章　学习成就评定" },
      { slug: "13", title: "第十三章　学习过程的测量" },
    ],
  },
];
